"""Final assembler — merges chapter files into the finished manual.

Supports two modes:

* **full**: concatenates all chapters into ``output/Exam_Manual.md`` with
  a global table of contents, chapter numbering, metadata, and normalised
  image paths.
* **topic**: writes a single focus chapter to
  ``output/Exam_Manual_<slug>.md`` with metadata and normalised paths.

Usage::

    from pipeline.merge import merge_chapters
    from utils.config import ConfigManager

    cfg = ConfigManager()
    output_path = merge_chapters(
        chapters_md, index_entries, cfg, focus_topic="Vector Spaces",
    )
"""

from __future__ import annotations

import re
import unicodedata
from datetime import datetime, timezone
from pathlib import Path

from core.models import IndexEntry, Topic
from pipeline.template_engine import render_toc
from utils.config import ConfigManager
from utils.logger import get_logger

logger = get_logger(__name__)


# ── Slug helper ──────────────────────────────────────────────────────────────


def _slugify(text: str) -> str:
    nfkd = unicodedata.normalize("NFKD", text)
    ascii_text = nfkd.encode("ascii", "ignore").decode("ascii")
    slug = ascii_text.lower()
    slug = re.sub(r"[^a-z0-9 \-]", "", slug)
    slug = re.sub(r"[\s\-]+", "-", slug).strip("-")
    return slug


# ── Parsing helpers ──────────────────────────────────────────────────────────


def _extract_title(chapter_md: str) -> str:
    """Extract the ``# `` heading from a chapter."""
    for line in chapter_md.split("\n"):
        m = re.match(r"^#\s+(.+)", line)
        if m:
            return m.group(1).strip()
    return "Untitled"


def _strip_local_toc(chapter_md: str) -> str:
    """Remove the local TOC block that appears right after the ``# `` title.

    The TOC block consists of lines matching ``- […](#…)`` (optionally
    indented) between the title and the first ``## `` heading.
    """
    lines = chapter_md.split("\n")
    title_idx = -1
    first_h2_idx = len(lines)

    for i, line in enumerate(lines):
        if re.match(r"^#\s+", line) and title_idx < 0:
            title_idx = i
        if re.match(r"^##\s+", line) and i > title_idx:
            first_h2_idx = i
            break

    if title_idx < 0:
        return chapter_md

    # Collect TOC lines: from title_idx+1 to first_h2_idx, only ``- […]`` lines
    toc_start = title_idx + 1
    toc_end = toc_start
    for i in range(toc_start, first_h2_idx):
        stripped = lines[i].strip()
        if re.match(r"^(-\s+\[|\s+-\s+\[)", stripped):
            toc_end = i + 1
        elif stripped == "":
            # blank line within TOC block — skip it
            continue
        else:
            break

    # Remove TOC lines (and any trailing blank lines)
    new_lines = lines[:toc_start] + lines[toc_end:]
    # Collapse multiple blank lines after title
    return "\n".join(new_lines)


def _extract_h2_headings(chapter_md: str) -> list[str]:
    """Return ``## `` heading texts from a chapter."""
    headings: list[str] = []
    for line in chapter_md.split("\n"):
        m = re.match(r"^##\s+(.+)", line)
        if m:
            headings.append(m.group(1).strip())
    return headings


# ── Ordering ─────────────────────────────────────────────────────────────────


def _sort_chapters_by_syllabus(
    chapters_md: list[str],
    topics: list[Topic] | None,
) -> list[str]:
    """Re-order chapters by ascending ``syllabus_position`` when available.

    Falls back to original list order for chapters whose topic has no
    syllabus position.
    """
    if not topics:
        return chapters_md

    topic_order: dict[str, int | None] = {}
    for t in topics:
        topic_order[t.name.lower()] = getattr(t, "syllabus_position", None)

    def _sort_key(md: str) -> tuple[int, int]:
        title = _extract_title(md).lower()
        pos = topic_order.get(title)
        if pos is not None:
            return (0, pos)
        return (1, chapters_md.index(md))

    return sorted(chapters_md, key=_sort_key)


# ── Metadata ─────────────────────────────────────────────────────────────────


def _build_metadata(cfg: ConfigManager, *, scope: str, topic_count: int) -> str:
    """Render an HTML-comment metadata block."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    depth = cfg.get("generation.depth_level", 5)
    lines = [
        "<!--",
        f"  Generated by ExamBookGenerator",
        f"  Date: {now}",
        f"  Scope: {scope}",
        f"  Topics: {topic_count}",
        f"  Depth level: {depth}",
        "-->",
    ]
    return "\n".join(lines)


# ── Image path normalisation ─────────────────────────────────────────────────


def _normalise_image_paths(chapter_md: str) -> str:
    """Ensure ``![…](…)`` paths are relative to ``output/``."""
    def _replace(m: re.Match) -> str:
        alt = m.group(1)
        path = m.group(2)
        if path.startswith("http://") or path.startswith("https://"):
            return m.group(0)
        if not path.startswith("output/"):
            path = f"output/{path}"
        return f"![{alt}]({path})"

    return re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", _replace, chapter_md)


# ── Global TOC ───────────────────────────────────────────────────────────────


def _consolidate_entries(
    chapters_md: list[str],
    provided_entries: list[IndexEntry],
) -> list[IndexEntry]:
    """Build a consolidated list of ``IndexEntry`` for the global TOC.

    Always rebuilds from the actual chapter headings (after numbering)
    so that TOC anchors match the real ``# N. Title`` headings.
    The *provided_entries* are used only as a fallback when no chapters
    are available (e.g. empty merge).
    """
    if not chapters_md:
        return provided_entries

    entries: list[IndexEntry] = []
    order = 0
    for md in chapters_md:
        title = _extract_title(md)
        entries.append(
            IndexEntry(
                title=title,
                anchor=_slugify(title),
                level=1,
                order=order,
            )
        )
        order += 1

    return entries


# ── Chapter numbering ────────────────────────────────────────────────────────


def _add_numbering(chapter_md: str, number: int) -> str:
    """Prepend a chapter number to the ``# `` title.

    ``## Linear Algebra`` → ``# 1. Linear Algebra``
    """
    lines = chapter_md.split("\n")
    for i, line in enumerate(lines):
        m = re.match(r"^(#\s+)(.+)", line)
        if m:
            lines[i] = f"{m.group(1)}{number}. {m.group(2)}"
            break
    return "\n".join(lines)


# ── Main public function ─────────────────────────────────────────────────────


def merge_chapters(
    chapters_md: list[str],
    index_entries: list[IndexEntry],
    cfg: ConfigManager,
    *,
    topics: list[Topic] | None = None,
    focus_topic: str | None = None,
) -> Path:
    """Merge chapter Markdown files into the final output.

    Parameters
    ----------
    chapters_md:
        List of rendered chapter Markdown strings (from
        :func:`~pipeline.chapter_generator.generate_chapter`).
    index_entries:
        Consolidated index entries for the global TOC.
    cfg:
        Project configuration.
    topics:
        Topic list (used for syllabus ordering).
    focus_topic:
        When set, triggers topic-scope output with a slugified filename.

    Returns
    -------
    Path
        Path to the written output file.
    """
    scope = cfg.get("generation.scope", "full")

    if scope == "topic" or focus_topic:
        return _merge_topic(chapters_md, cfg, focus_topic=focus_topic or "")

    return _merge_full(chapters_md, index_entries, cfg, topics=topics)


def _merge_full(
    chapters_md: list[str],
    index_entries: list[IndexEntry],
    cfg: ConfigManager,
    *,
    topics: list[Topic] | None = None,
) -> Path:
    """Full-scope merge → ``output/Exam_Manual.md``."""
    if not chapters_md:
        logger.warning("No chapters to merge — writing empty manual")
        return _write_output("# Exam Manual\n\nNo chapters generated.\n", "Exam_Manual.md")

    # ── Sort by syllabus if applicable ─────────────────────────────────
    has_syllabus = any(
        getattr(t, "order_source", None) == "syllabus" for t in (topics or [])
    )
    if has_syllabus:
        chapters_md = _sort_chapters_by_syllabus(chapters_md, topics)

    # ── Process chapters (strip TOC, normalize, number) ────────────────
    processed_chapters: list[str] = []
    for idx, md in enumerate(chapters_md, 1):
        md = _strip_local_toc(md)
        md = _normalise_image_paths(md)
        md = _add_numbering(md, idx)
        processed_chapters.append(md)

    # ── Build TOC from actual numbered headings ────────────────────────
    consolidated = _consolidate_entries(processed_chapters, index_entries)

    # ── Build output ───────────────────────────────────────────────────
    parts: list[str] = []

    # Metadata
    parts.append(_build_metadata(cfg, scope="full", topic_count=len(processed_chapters)))
    parts.append("")

    # Title
    parts.append("# Exam Manual")
    parts.append("")

    # Global TOC
    global_toc = render_toc(consolidated)
    if global_toc:
        parts.append(global_toc)
        parts.append("")

    # Separator
    parts.append("---")
    parts.append("")

    # Chapters with separators
    for md in processed_chapters:
        parts.append(md.strip())
        parts.append("")
        parts.append("---")
        parts.append("")

    content = "\n".join(parts)
    return _write_output(content, "Exam_Manual.md")


def _merge_topic(
    chapters_md: list[str],
    cfg: ConfigManager,
    *,
    focus_topic: str = "",
) -> Path:
    """Topic-scope merge → ``output/Exam_Manual_<slug>.md``."""
    if not chapters_md:
        slug = _slugify(focus_topic) if focus_topic else "focus"
        filename = f"Exam_Manual_{slug}.md"
        return _write_output("# Focus\n\nNo content generated.\n", filename)

    chapter = chapters_md[0]  # single chapter
    chapter = _strip_local_toc(chapter)
    chapter = _normalise_image_paths(chapter)

    # Build slug for filename
    slug = _slugify(focus_topic) if focus_topic else "focus"
    filename = f"Exam_Manual_{slug}.md"

    # Build metadata
    metadata = _build_metadata(cfg, scope="topic", topic_count=1)

    # The chapter already has its own local TOC — keep it.
    # Just wrap with metadata and write.
    parts = [
        metadata,
        "",
        chapter.strip(),
        "",
    ]

    content = "\n".join(parts)
    return _write_output(content, filename)


# ── Output ───────────────────────────────────────────────────────────────────


def _write_output(content: str, filename: str) -> Path:
    """Write *content* to ``output/<filename>`` and return the path."""
    out_dir = Path("output")
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / filename
    path.write_text(content, encoding="utf-8")
    logger.info("Output written to %s (%d chars)", path, len(content))
    return path
